# AWS Lambda Permission
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission

variable "action" {
  description = "AWS Lambda action you want to allow in this statement. Defaults to `lambda:InvokeFunction`."
  type        = string
  default     = "lambda:InvokeFunction"
}

variable "function_name" {
  description = "Name of the Lambda function."
  type        = string
}

variable "principal" {
  description = "Principal who is getting this permission."
  type        = string
  default     = null
}

variable "source_arn" {
  description = "ARN of the invokable AWS resource."
  type        = string
  default     = null
}

variable "statement_id" {
  description = "A unique statement identifier. By default generated by Terraform."
  type        = string
  default     = null
}
