name: 'Terraform fmt check'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, develop]

jobs:
  fmt-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9

    - name: Terraform fmt check
      run: terraform fmt -check -recursive
